version: '3.1'
services:
  mysql_dev:
    container_name: 'invest_pro_dev'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ../../../env/.env.dev
    ports:
      - '${DATABASE_PORT}:3306'
    restart: unless-stopped
    volumes:
      - mysql_dev_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
volumes:
  mysql_dev_data:
